# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    uses: LouisBrunner/.github/.github/workflows/lint-all.yml@main
    permissions:
      actions: read
      contents: read
      statuses: write
      pull-requests: write

  vet:
    uses: LouisBrunner/.github/.github/workflows/lint-go.yml@main
    permissions:
      contents: read

  test:
    name: Test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Test
        run: |
          make test-ci
          make coverage-ci

      - name: Publish results
        if: always()
        uses: LouisBrunner/.github/.github/actions/junit-cobertura@main
        with:
          junit-file: report.xml
          cobertura-file: cobertura.xml
